services:
  quiz-app:
    build: . # Tells Docker Compose to build the image from the Dockerfile in the current directory
    container_name: multiplayer_quiz_app
    ports:
      - "4000:3000" # Map port 4000 on the host to port 3src/app/server.js
    restart: unless-stopped
    environment:
      - NODE_ENV=production # Example environment variable
    networks:
      - npm_network

# Add this at the top level of your docker-compose.yml
networks:
  npm_network:
    external: true